#!/bin/bash

#exec qemu-system-x86_64 -enable-kvm \
#       -cpu host \
#       -m 512M \
#       -drive file=ArchVM-1.img,if=virtio \
#       -netdev user,id=vmnic,hostname=archvm1 \
#       -device virtio-net,netdev=vmnic,mac="72:49:ef:dc:e4:01" \
#       -name "Arch VM 1" \
#       "$@"

USERID=$(whoami)
precreationg=$(ip tuntap list | /usr/bin/cut -d: -f1 | /usr/bin/sort)
sudo ip tuntap add user $USERID mode tap
postcreation=$(ip tuntap list | /usr/bin/cut -d: -f1 | /usr/bin/sort)
IFACE=$(comm -13 <(echo "$precreationg") <(echo "$postcreation"))

echo $IFACE

macaddr='72:49:ef:dc:e4:01'

qemu-system-x86_64 -enable-kvm \
       -cpu host \
       -m 512M \
       -name "Arch VM 1" \
       -drive file=ArchVM-1.img \
       -net nic,macaddr=$macaddr -net tap,ifname="$IFACE" \
       $*

#./startvm -boot once=d -cdrom
