#!/bin/bash

#exec qemu-system-x86_64 -enable-kvm \
#       -cpu host \
#       -m 512M \
#       -drive file=ArchVM-2.img,if=virtio \
#       -netdev user,id=vmnic,hostname=archvm2 \
#       -device virtio-net,netdev=vmnic,mac="72:49:ef:dc:e4:02" \
#       -name "Arch VM 2" \
#       "$@"

USERID=$(whoami)
precreationg=$(ip tuntap list | /usr/bin/cut -d: -f1 | /usr/bin/sort)
sudo ip tuntap add user $USERID mode tap
postcreation=$(ip tuntap list | /usr/bin/cut -d: -f1 | /usr/bin/sort)
IFACE=$(comm -13 <(echo "$precreationg") <(echo "$postcreation"))

macaddr='72:49:ef:dc:e4:02'

echo $IFACE

qemu-system-x86_64 -enable-kvm \
       -cpu host \
       -m 512M \
       -drive file=ArchVM-2.img \
       -net nic,macaddr=$macaddr -net tap,ifname="$IFACE" \
       $*
